from sqlalchemy import JSON, Column, DateTime, Float, ForeignKey, Integer, String
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from app.db.base_class import Base
from app.core.constants import RiskLevel


class RiskSummary(Base):
    """
    Stores the current aggregated risk state for a user.
    Updated in-place on every new assessment submission.
    For historical evolution, see AssessmentResponse.risk_level per row.
    """

    __tablename__ = "risk_summaries"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), unique=True, nullable=False)

    # Emotional risk level from the ML risk classifier ("Low"/"Medium"/"High"/"Critical")
    current_risk_level = Column(String, default=RiskLevel.LOW.value)
    # Confidence score of the ML prediction (0.0 to 1.0)
    prediction_confidence = Column(Float, default=1.0)

    # Dropout prediction from the RandomForest model
    dropout_probability = Column(Float, default=0.0)   # 0.0 to 1.0
    dropout_risk = Column(String, default=RiskLevel.LOW.value)        # "Low" / "Medium" / "High"

    # Contextual recommendations generated by recommendation_service
    # Stored as a JSON array of strings so the frontend can render them directly.
    recommendations = Column(JSON, default=list)

    last_updated = Column(
        DateTime(timezone=True), onupdate=func.now(), server_default=func.now()
    )

    # Relationship back to the user
    user = relationship("User", back_populates="risk_summary")
