"""Add recommendations to risk_summaries

Revision ID: 09ec1ad9410e
Revises: e68b40669db7
Create Date: 2026-03-03 15:42:02.546792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09ec1ad9410e'
down_revision: Union[str, Sequence[str], None] = 'e68b40669db7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_summaries', sa.Column('recommendations', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_summaries', 'recommendations')
    # ### end Alembic commands ###
