"""Add Hito grading system to academic profile

Revision ID: 11bf535e4730
Revises: 9a728e880737
Create Date: 2026-02-24 14:48:00.917521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11bf535e4730'
down_revision: Union[str, Sequence[str], None] = '9a728e880737'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic_profiles', sa.Column('hito2_procesual', sa.Float(), nullable=True))
    op.add_column('academic_profiles', sa.Column('hito2_nota', sa.Float(), nullable=True))
    op.add_column('academic_profiles', sa.Column('hito3_procesual', sa.Float(), nullable=True))
    op.add_column('academic_profiles', sa.Column('hito3_nota', sa.Float(), nullable=True))
    op.add_column('academic_profiles', sa.Column('hito4_procesual', sa.Float(), nullable=True))
    op.add_column('academic_profiles', sa.Column('hito4_nota', sa.Float(), nullable=True))
    op.add_column('academic_profiles', sa.Column('hito5_procesual', sa.Float(), nullable=True))
    op.add_column('academic_profiles', sa.Column('hito5_nota', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('academic_profiles', 'hito5_nota')
    op.drop_column('academic_profiles', 'hito5_procesual')
    op.drop_column('academic_profiles', 'hito4_nota')
    op.drop_column('academic_profiles', 'hito4_procesual')
    op.drop_column('academic_profiles', 'hito3_nota')
    op.drop_column('academic_profiles', 'hito3_procesual')
    op.drop_column('academic_profiles', 'hito2_nota')
    op.drop_column('academic_profiles', 'hito2_procesual')
    # ### end Alembic commands ###
