"""Add share_with_psychologist to assessment response

Revision ID: 681f4f0f3c9b
Revises: 09ec1ad9410e
Create Date: 2026-03-06 18:44:48.166566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '681f4f0f3c9b'
down_revision: Union[str, Sequence[str], None] = '09ec1ad9410e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_responses', sa.Column('share_with_psychologist', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessment_responses', 'share_with_psychologist')
    # ### end Alembic commands ###
