"""add_ai_analysis_to_emotional_diary

Revision ID: 77e932631262
Revises: d719410ca0bc
Create Date: 2026-03-11 11:00:18.393021

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "77e932631262"
down_revision: Union[str, Sequence[str], None] = "d719410ca0bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "emotional_diary", sa.Column("emotion_ai", sa.String(), nullable=True)
    )
    op.add_column(
        "emotional_diary", sa.Column("emotion_scores", sa.JSON(), nullable=True)
    )
    op.add_column(
        "emotional_diary",
        sa.Column("analysis_created_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("emotional_diary", "analysis_created_at")
    op.drop_column("emotional_diary", "emotion_scores")
    op.drop_column("emotional_diary", "emotion_ai")
    # ### end Alembic commands ###
