"""add_emotional_diary_table

Revision ID: d719410ca0bc
Revises: 681f4f0f3c9b
Create Date: 2026-03-10 11:14:45.969331

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d719410ca0bc"
down_revision: Union[str, Sequence[str], None] = "681f4f0f3c9b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "emotional_diary",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("experience", sa.Text(), nullable=True),
        sa.Column("activities", sa.Text(), nullable=True),
        sa.Column("emotion", sa.String(), nullable=False),
        sa.Column("emotion_color", sa.String(), nullable=False),
        sa.Column("wellbeing_level", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "date", name="uq_user_diary_date"),
    )
    op.create_index(
        op.f("ix_emotional_diary_created_at"),
        "emotional_diary",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_emotional_diary_id"), "emotional_diary", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_emotional_diary_user_id"), "emotional_diary", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_emotional_diary_user_id"), table_name="emotional_diary")
    op.drop_index(op.f("ix_emotional_diary_id"), table_name="emotional_diary")
    op.drop_index(op.f("ix_emotional_diary_created_at"), table_name="emotional_diary")
    op.drop_table("emotional_diary")
    # ### end Alembic commands ###
