"""Add dropout_probability to assessment_response

Revision ID: e68b40669db7
Revises: 946b9460e61d
Create Date: 2026-02-24 15:41:49.620080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e68b40669db7'
down_revision: Union[str, Sequence[str], None] = '946b9460e61d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_responses', sa.Column('dropout_probability', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessment_responses', 'dropout_probability')
    # ### end Alembic commands ###
