"""add_energy_and_sleep_to_checkins

Revision ID: ffa143369ca9
Revises: ee919c602f91
Create Date: 2026-01-26 17:31:32.032847

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ffa143369ca9"
down_revision: Union[str, Sequence[str], None] = "ee919c602f91"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_assessment_responses_assessment_id"),
        "assessment_responses",
        ["assessment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assessment_responses_created_at"),
        "assessment_responses",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assessment_responses_user_id"),
        "assessment_responses",
        ["user_id"],
        unique=False,
    )
    op.add_column(
        "emotional_checkins", sa.Column("energy_level", sa.Integer(), nullable=True)
    )
    op.add_column(
        "emotional_checkins", sa.Column("sleep_hours", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_emotional_checkins_created_at"),
        "emotional_checkins",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_emotional_checkins_user_id"),
        "emotional_checkins",
        ["user_id"],
        unique=False,
    )
    op.alter_column(
        "users",
        "hashed_password",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "hashed_password",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.drop_index(
        op.f("ix_emotional_checkins_user_id"), table_name="emotional_checkins"
    )
    op.drop_index(
        op.f("ix_emotional_checkins_created_at"), table_name="emotional_checkins"
    )
    op.drop_column("emotional_checkins", "sleep_hours")
    op.drop_column("emotional_checkins", "energy_level")
    op.drop_index(
        op.f("ix_assessment_responses_user_id"), table_name="assessment_responses"
    )
    op.drop_index(
        op.f("ix_assessment_responses_created_at"), table_name="assessment_responses"
    )
    op.drop_index(
        op.f("ix_assessment_responses_assessment_id"), table_name="assessment_responses"
    )
    # ### end Alembic commands ###
