"""allow_multiple_daily_entries

Revision ID: 1d367e018e2d
Revises: ecc9f28ccccf
Create Date: 2026-03-30 12:21:29.497930

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1d367e018e2d'
down_revision: Union[str, Sequence[str], None] = 'ecc9f28ccccf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_diary_date'), 'emotional_diary', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_user_diary_date'), 'emotional_diary', ['user_id', 'date'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
