"""add academic_pressure column

Revision ID: 672a9336714f
Revises: ffa143369ca9
Create Date: 2026-01-29 19:52:33.806527

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "672a9336714f"
down_revision: Union[str, Sequence[str], None] = "ffa143369ca9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_clinical_notes_student_id"), table_name="clinical_notes")
    op.add_column(
        "emotional_checkins",
        sa.Column("academic_pressure", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("emotional_checkins", "academic_pressure")
    op.create_index(
        op.f("ix_clinical_notes_student_id"),
        "clinical_notes",
        ["student_id"],
        unique=False,
    )
    # ### end Alembic commands ###
