"""Add AcademicRecord and update mappings

Revision ID: 9193cb28b031
Revises: 77e932631262
Create Date: 2026-03-20 17:28:15.609487

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9193cb28b031'
down_revision: Union[str, Sequence[str], None] = '77e932631262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('enrolled_credits', sa.Integer(), nullable=True),
    sa.Column('failed_classes', sa.Integer(), nullable=True),
    sa.Column('hito2_procesual', sa.Float(), nullable=True),
    sa.Column('hito2_nota', sa.Float(), nullable=True),
    sa.Column('hito3_procesual', sa.Float(), nullable=True),
    sa.Column('hito3_nota', sa.Float(), nullable=True),
    sa.Column('hito4_procesual', sa.Float(), nullable=True),
    sa.Column('hito4_nota', sa.Float(), nullable=True),
    sa.Column('hito5_procesual', sa.Float(), nullable=True),
    sa.Column('hito5_nota', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_academic_records_id'), 'academic_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_academic_records_id'), table_name='academic_records')
    op.drop_table('academic_records')
    # ### end Alembic commands ###
