"""Add academic profile and dropout prediction

Revision ID: 9a728e880737
Revises: 672a9336714f
Create Date: 2026-02-24 14:31:52.422777

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a728e880737"
down_revision: Union[str, Sequence[str], None] = "672a9336714f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "academic_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("course", sa.String(), nullable=True),
        sa.Column("scholarship_holder", sa.Boolean(), nullable=True),
        sa.Column("tuition_fees_up_to_date", sa.Boolean(), nullable=True),
        sa.Column("current_semester", sa.Integer(), nullable=True),
        sa.Column("units_approved", sa.Integer(), nullable=True),
        sa.Column("current_gpa", sa.Float(), nullable=True),
        sa.Column("age_at_enrollment", sa.Integer(), nullable=True),
        sa.Column("gender", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_academic_profiles_id"), "academic_profiles", ["id"], unique=False
    )
    op.add_column(
        "risk_summaries", sa.Column("dropout_probability", sa.Float(), nullable=True)
    )
    op.add_column(
        "risk_summaries", sa.Column("dropout_risk", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("risk_summaries", "dropout_risk")
    op.drop_column("risk_summaries", "dropout_probability")
    op.drop_index(op.f("ix_academic_profiles_id"), table_name="academic_profiles")
    op.drop_table("academic_profiles")
    # ### end Alembic commands ###
