"""Add AcademicSubjectGrade for per-subject hitos

Revision ID: a4d526014377
Revises: 9193cb28b031
Create Date: 2026-03-20 17:31:55.631880

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a4d526014377'
down_revision: Union[str, Sequence[str], None] = '9193cb28b031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_subject_grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(), nullable=False),
    sa.Column('hito2_procesual', sa.Float(), nullable=True),
    sa.Column('hito2_nota', sa.Float(), nullable=True),
    sa.Column('hito3_procesual', sa.Float(), nullable=True),
    sa.Column('hito3_nota', sa.Float(), nullable=True),
    sa.Column('hito4_procesual', sa.Float(), nullable=True),
    sa.Column('hito4_nota', sa.Float(), nullable=True),
    sa.Column('hito5_procesual', sa.Float(), nullable=True),
    sa.Column('hito5_nota', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_subject_grades_id'), 'academic_subject_grades', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_academic_subject_grades_id'), table_name='academic_subject_grades')
    op.drop_table('academic_subject_grades')
    # ### end Alembic commands ###
