"""Remove one-diary-per-day restriction

Revision ID: ecc9f28ccccf
Revises: a4d526014377
Create Date: 2026-03-20 17:47:08.857889

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ecc9f28ccccf'
down_revision: Union[str, Sequence[str], None] = 'a4d526014377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
